### ISSUE TITLE
Strainer::Error::CookbookNotFound - Could not find 'foo' in any of the sources.

### ISSUE THREAD

**Issue by akatz** [customink/strainer#37]
Using berkshelf, with a particular cookbook pointed at a local path, I get this errror when trying to 
`bundle exec strainer test foo -d`

``` text
[DEBUG]   Called Strainer::Cli#test with ["foo"]
[DEBUG]   Created new Strainer::Runner with ["foo"], options: {"strainer_file"=>"Strainerfile", "sandbox"=>"/var/folders/kn/q1rhkdm14bj6l4lr5cw3g5wm0000gn/T/d20130808-7970-1i2xqsv", "debug"=>true, "color"=>true, "fail_fast"=>false}
[DEBUG]   Detected as a chef repo
[DEBUG]   Sandbox#load_cookbooks(["foo"])
[DEBUG]   Sandbox#load_cookbook('"foo"')
[DEBUG]   Setting Sandbox#cookbooks_paths to ["/Users/akatz/projects/foo-chef/cookbooks"]
[DEBUG]     did not find 'foo' in any of the sources - resorting to the default cookbook_store...
Exception `Errno::EEXIST' at /Users/akatz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/fileutils.rb:244 - File exists - /Users/akatz/.berkshelf/cookbooks
Exception `Strainer::Error::CookbookNotFound' at /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bundler/gems/strainer-cde81aaaac51/lib/strainer/sandbox.rb:176 - Could not find 'foo' in any of the sources.
Strainer::Error::CookbookNotFound - Could not find 'foo' in any of the sources.
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bundler/gems/strainer-cde81aaaac51/lib/strainer/sandbox.rb:176:in `load_cookbook'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bundler/gems/strainer-cde81aaaac51/lib/strainer/sandbox.rb:147:in `block in load_cookbooks'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bundler/gems/strainer-cde81aaaac51/lib/strainer/sandbox.rb:147:in `collect'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bundler/gems/strainer-cde81aaaac51/lib/strainer/sandbox.rb:147:in `load_cookbooks'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bundler/gems/strainer-cde81aaaac51/lib/strainer/sandbox.rb:45:in `initialize'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bundler/gems/strainer-cde81aaaac51/lib/strainer/runner.rb:36:in `new'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bundler/gems/strainer-cde81aaaac51/lib/strainer/runner.rb:36:in `initialize'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bundler/gems/strainer-cde81aaaac51/lib/strainer/cli.rb:77:in `new'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bundler/gems/strainer-cde81aaaac51/lib/strainer/cli.rb:77:in `test'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bundler/gems/strainer-cde81aaaac51/lib/strainer/cli.rb:35:in `dispatch'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bundler/gems/strainer-cde81aaaac51/bin/strainer:8:in `<top (required)>'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bin/strainer:19:in `load'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bin/strainer:19:in `<main>'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bin/ruby_noexec_wrapper:14:in `eval'
   /Users/akatz/.rvm/gems/ruby-1.9.3-p392@chef/bin/ruby_noexec_wrapper:14:in `<main>'
Releasing ManagedGssBufferDesc at 7f8e8cd5ed10
```

**Comment by rshade** [comment]
I am having the same problem with Strainer 3.4.0 and Berkshelf 3.3.0 with git repos. 
https://github.com/RightScale-Services-Cookbooks/rsc_gluster/blob/STRAINER_3_4_0/Gemfile
https://github.com/RightScale-Services-Cookbooks/rsc_gluster/blob/STRAINER_3_4_0/Berksfile#L5
I am getting `Strainer::Error::CookbookNotFound - Could not find 'gluster' in any of the sources`. even though `berks install` works. https://travis-ci.org/RightScale-Services-Cookbooks/rsc_gluster/jobs/76630938
